# GitHub Copilot Init - Smart Context Management
# Auto-generated by @drkmattrlabs/copilot_init

if [[ -f "$HOME/.copilot_init.sh" ]]; then
    source "$HOME/.copilot_init.sh"
fi

# Auto-refresh context on directory change
export COPILOT_PREV_DIR="$PWD"
copilot_check_dir_change() {
    if [[ "$PWD" != "$COPILOT_PREV_DIR" ]]; then
        load_project_context 2>/dev/null
        export COPILOT_PREV_DIR="$PWD"
    fi
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd copilot_check_dir_change

# Aliases
alias copilot='copilot_status'
alias cstatus='copilot_status'
alias crefresh='copilot_refresh'
alias nextbuild='autobuild_next'
alias railsmerge='automerge_rails'

# Safety: prevent force push to main
git() {
    if [[ "$1" == "push" ]] && [[ "$*" =~ "--force" ]] && [[ "$(get_current_branch 2>/dev/null)" =~ ^(main|master)$ ]]; then
        echo "⚠️  WARNING: Force push to main/master is blocked"
        echo "   Use: command git push --force (if you're sure)"
        return 1
    fi
    command git "$@"
}
